# Generated by Django 6.1 on 2026-08-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_auth_type_to_device_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesession',
            name='django_session_key',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='devicesession',
            name='refresh_token_jti',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
