# Generated by Django 6.1 on 2026-08-26 12:48

from django.db import migrations, models

import apps.chat.models.conversation


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_attachment_message_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.chat.models.conversation.conversation_avatar_upload_to),
        ),
        migrations.AddField(
            model_name='conversation',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
